# Generated by Django 3.1 on 2020-10-17 10:45

import calculation.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_period', models.DateField(auto_now_add=True)),
                ('end_period', models.DateField(blank=True, null=True)),
                ('per_head', models.CharField(blank=True, max_length=255, null=True)),
                ('total_expenses', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_pic', models.ImageField(blank=True, null=True, upload_to=calculation.models.upload_pic_image_path)),
                ('group_name', models.CharField(max_length=255)),
                ('group_type', models.CharField(max_length=255)),
                ('group_country', models.CharField(max_length=255)),
                ('group_created_at', models.DateTimeField(auto_now_add=True)),
                ('group_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_admin', to=settings.AUTH_USER_MODEL)),
                ('group_members', models.ManyToManyField(related_name='group_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=calculation.models.upload_bill_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='TotalExpenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('calculation_period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Total_cal_period', to='calculation.calculationperiod')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_id_total', to='calculation.groups')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('calculation_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Personal_cal_period', to='calculation.calculationperiod')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_id_personal', to='calculation.groups')),
                ('spender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spender_id_personal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creaded_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('friend_id', models.ManyToManyField(related_name='friend_id', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinalTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('calculation_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_cal_period', to='calculation.calculationperiod')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_id_final', to='calculation.groups')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bill', models.ImageField(blank=True, null=True, upload_to=calculation.models.upload_bill_image_path)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('exp_note', models.CharField(blank=True, max_length=255)),
                ('calculation_period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cal_period', to='calculation.calculationperiod')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exp_group_id', to='calculation.groups')),
                ('spender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='calculationperiod',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cal_group_id', to='calculation.groups'),
        ),
    ]
